### ISSUE TITLE
beLayout does not applied

### ISSUE THREAD

**Issue by alorotom** [pluspol-interactive/templavoilaplus#230]
Hello together!

**Issue details.**

Administration log of TYPO3 contains the next issue: "Core: Error handler (BE): PHP Warning: preg_replace_callback(): Compilation failed: invalid range in character class at offset 11 in /usr/local/var/www/web/typo3conf/ext/templavoilaplus/Classes/Controller/BackendLayoutController.php line 1720".

**Environment details.**

PHP 7.3.2
TYPO3 9.5.4
TVPlus 7.3.0
 
The beLayout feature (like in old versions of TV) does not work in TVPlus.

**Some other details.**

Two of content elements were displayed in BE like this by default:

«field_content1» «field_content2»

Could you please describe how to configure the next view?

«field_content1»
«field_content2»

It was possible to use the next code for changing of view in early versions of TV:

```
<?xml version="1.0" encoding="utf-8" standalone="yes" ?>
<T3DataStructure>
	<meta type="array">
		<langDisable>1</langDisable>
		<beLayout><![CDATA[
			<table width="100%">
				<tr>
					<td>###field_content1###</td>
				</tr>
				<tr>
					<td>###field_content2###</td>
				</tr>
			</table>
		]]>
		</beLayout>
	</meta>
	<ROOT type="array">
...
```

This code does not work on actual version of TVPlus. Could you please clarify how to use beLayout?

Regards,
AAL.

**Comment by jpmschuler** [comment]
n.b.: In 8LTS this works like a charm. With 7.3.1 (7.3.0.1 in composer mode) as well as all older versions.

**Comment by alorotom** [comment]
Thank you for the fast reply. Could you please clarify is it possible and how to update TVPlus installed from TER on TYPO3 9.5.5 using composer?

**Comment by jpmschuler** [comment]
I'd never say it works in 9LTS. TER and composer are not compatible, it is an architecture choice. You could however download a tagged version from git and replace the files in the filesystems. However it worked in 7.3.0 as well so that shouldn't help with your problem anyways.

**Comment by alorotom** [comment]
OK, thank you very much. I hope that upgrade of php to version 7.3.3 will solve this issue. If not, I will perform some experiments and downgrade TYPO3 to 8LTS. Have a great weekend!

**Comment by alorotom** [comment]
So, fast (but not good) fix of this issue is commenting of code related to "//replace long markers" on ....typo3conf/ext/templavoilaplus/Classes/Controller/BackendLayoutController.php. Lines from 1720 to 1726, till "//remove not used markers".

**Comment by opi99** [comment]
It's about "preg: Compilation failed" so this issue seams to depend on PHP version.
@alorotom Which PHP version on which OS do you use?
@jpmschuler Which PHP version on which OS do you use? (As it is a warning, maybe it isn't shown?)

The regex in question is `/###(LLL:[\w-\/:]+?\.xml\:[\w-\.]+?)###/` it seams the `-` sign is interpreted as range char instead of the sign himself.
Does it work if you both replace the minus sign with `\-` (add escape char)?

**Comment by jpmschuler** [comment]
> @jpmschuler Which PHP version on which OS do you use? (As it is a warning, maybe it isn't shown?)
PHP 7.0.33-0ubuntu0.16.04.2 didn't have the chance to test 9LTS yet, 8LTS works like a charm.

**Comment by alorotom** [comment]
Hello everyone,

Webserver: Apache/2.4.38 (Unix) PHP/7.3.2
OS: Darwin 18.2.0

/###(LLL:[\w\-\/:]+?\.xml\:[\w\-\.]+?)###/ -- it works.

Many thanks!

**Comment by opi99** [comment]
@alorotom Thx for feedback
@jpmschuler Can you check if it still works with escaping on your system?

**Comment by jpmschuler** [comment]
I applied f2c9ec7 as a patch and everything still works like a charm in 8LTS, still no errors in log with PHP 7.0.33-0ubuntu0.16.04.2 
<img width="1094" alt="Bildschirmfoto 2019-04-07 um 22 33 50" src="https://user-images.githubusercontent.com/12411176/55689494-50a4a280-5985-11e9-854a-a583e89b745e.png">
